version: '3.3' 
services:  
  web: 
    build: 
      context: ./ 
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: web 
    restart: always 
    ports: 
     - "3000:80"

  e2e: 
    build:   
      context: ./  
      dockerfile: Cypress.Dockerfile  
    container_name: cypress
    depends_on: 
      - web 
    environment:  
      - CYPRESS_baseUrl=http://localhost:3000
    command: npx cypress run --reporter junit --reporter-options "mochaFile=/cypress/report/test-output-[hash].xml"
    network_mode: 'host' 
    volumes:  
      - "./cypress/reports:/web/cypress/report"
      - "./cypress/screenshots:/web/cypress/screenshots"  